GET http://localhost:8000/api/users

###
POST http://localhost:8000/api/login
content-type: application/json

{
    "username": "user1",
    "password": "1234"
}

###
POST http://localhost:8000/api/signup
content-type:application/json

{
    "username":"suresh",
    "firstname":"suresh",
    "lastname":"prajapati",
    "email":"email1@gmail.com",
    "password":"1234",
    "imageUrl":"profile-pics/profile-pic01.png",
    "description":"short description about user",
    "tasks":[
        {
            "name": "task2",
            "description":"task 1 s description",
            "duedate":"2019-10-29"
        }
    ]
}
###
PUT http://localhost:8000/api/user
Content-Type:application/json

{
    "username":"suresh",
    "email":"newemail@gmail.com",
    "firstname":"SURESH",
    "lastname":"PRAJAPATI"
}

###
PATCH http://localhost:8000/api/user/addtask
Content-Type:application/json

{
    "username":"suresh",
    "task":
         {
            "name": "task5",
            "description":"task 5 description",
            "duedate": "2019-11-15",
            "priority":4
        }
}

###
PATCH http://localhost:8000/api/user/removeTask/id
Content-Type:application/json

{
    "username":"suresh",
   "taskId": "5daa7bbf94a8f61243e9ad2e"
}


###
PATCH http://localhost:8000/api/user/edittask/id
Content-Type:application/json

{
    "username":"suresh",
   "taskId": "5daa7be294a8f61243e9ad31",
   "name":"play game",
   "description":"play game for a while",
   "priority":1,
   "duedate":"2019-12-12"
}



###
GET http://localhost:8000/api/useralltasks
Content-Type:application/json

{
    "username":"suresh"
}

###
GET http://localhost:8000/api/usertask/findbyname
content-type: application/json

{
    "username": "sunena",
    "taskName": "task2"
}

###
GET http://localhost:8000/api/usertask/findbyduedate
content-type: application/json

{
    "username": "sunena",
    "due": "2019-10-20"
}

###
GET http://localhost:8000/api/usertask1/findbypriority
content-type: application/json

{
    "username": "sunena",
    "priority": 1
}

###
GET http://localhost:8000/api/user/sunena